using System.ComponentModel;

namespace GanttChartSample.ViewModels.Base
{
    public abstract class ViewModelBase : INotifyPropertyChanged
    // OnPropertyChanged would be generated by Fody
    {
        public string Title { get; protected set; }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
